[package]
name = "vlc-module-tool"
version = "0.1.0"
authors = ["Alexandre Janniaux <alexandre.janniaux@gmail.com>"]
edition = "2018"

[dependencies]
dlopen = "0.1"
dlopen_derive = "0.1"
libc = "0.2"
