[package]
name = "vlc-module-tool"
version = "0.1.0"
authors = ["Alexandre Janniaux <alexandre.janniaux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
